{% set version = "0.2.2" %}
{% set python_min = "3.11" %}

package:
  name: datafiller
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datafiller/datafiller-{{ version }}.tar.gz
  sha256: cbf8487f6059f0967699ec897afd59122d553803f25095adf72db5a1e3c4e8bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba
    - scikit-learn
    - tqdm
    - pandas

test:
  imports:
    - datafiller
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CyrilJl/datafiller
  summary: A python package for easy data imputation
  doc_url: https://datafiller.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
